/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DocumentApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Documents": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NeonDbBorderlessPassportUploaderConnectionString": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
